# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
- lint
- test
- build

sast:
  stage: test
  needs: []
include:
- template: Security/SAST.gitlab-ci.yml

.pytest3.9:
  stage: test
  needs: []
  image: $CI_REGISTRY_IMAGE:ubuntu_base_python3.9
  before_script:
    - python3.9 -m pip install -r $CI_PROJECT_DIR/build/requirements.txt
    - python3.9 -m pip install pytest pytest-mock
    - mkdir $CI_PROJECT_DIR/local
    - mkdir $CI_PROJECT_DIR/local/keyword_features_hyperscan_databases


pytest3.9:
  extends: .pytest3.9
  script:
    - export MIM_OCR_CONFIG_PATH=$CI_PROJECT_DIR/config/test_mim_ocr_conf.yaml
    - cd $CI_PROJECT_DIR
    - python3.9 -m pytest tests/ --ignore=tests/optional_elements


pytest_3.9_optional_elements:
  extends: .pytest3.9
  variables:
    NER_RESOURCES_PATH: /dependencies/xlm-roberta-ner
  script:
    - export MIM_OCR_CONFIG_PATH=$CI_PROJECT_DIR/config/test_mim_ocr_conf.yaml
    - cd $CI_PROJECT_DIR
    - python3.9 -m pip install -r $CI_PROJECT_DIR/build/optional_requirements/ner_feature_requirements.txt
    - python3.9 -m pytest tests/optional_elements


.pytest3.10:
  stage: test
  needs: []
  image: $CI_REGISTRY_IMAGE:ubuntu_base_python3.10
  before_script:
    - python3.10 -m pip install -r $CI_PROJECT_DIR/build/requirements.txt
    - python3.10 -m pip install pytest pytest-mock
    - mkdir $CI_PROJECT_DIR/local
    - mkdir $CI_PROJECT_DIR/local/keyword_features_hyperscan_databases


pytest3.10:
  extends: .pytest3.10
  script:
    - export MIM_OCR_CONFIG_PATH=$CI_PROJECT_DIR/config/test_mim_ocr_conf.yaml
    - cd $CI_PROJECT_DIR
    - python3.10 -m pytest tests/ --ignore=tests/optional_elements


flake8:
  stage: lint
  image: python:3.9
  needs: []
  before_script:
    - python --version
    - pip install flake8
  script:
    - flake8

build_base_images:
  stage: build
  when: manual
  image: docker:stable
  services:
    - docker:dind
  needs: []
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --tag $CI_REGISTRY_IMAGE:base_ubuntu -f build/base_image/base_ubuntu.Dockerfile .
    - docker push $CI_REGISTRY_IMAGE:base_ubuntu
    - docker build --tag $CI_REGISTRY_IMAGE:ubuntu_base_python3.9 -f build/base_image/base_image_python.Dockerfile --build-arg python_version=3.9 .
    - docker push $CI_REGISTRY_IMAGE:ubuntu_base_python3.9
    - docker build --tag $CI_REGISTRY_IMAGE:ubuntu_base_python3.10 -f build/base_image/base_image_python.Dockerfile --build-arg python_version=3.10 .
    - docker push $CI_REGISTRY_IMAGE:ubuntu_base_python3.10
