name: Pytest
run-name: Pytest
on: [push]

env:
  MIM_OCR_CONFIG_PATH: /code/config/test_mim_ocr_conf.yaml

jobs:
  pytest:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/jerzyorlowskimim/mim-ocr-fork1_base_python3.9
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - run: mkdir /code
      - run: cd /code
      - name: Check out repository code
        uses: actions/checkout@v3

      - run: python3.9 -m pip install -r build/requirements.txt
      - run: python3.9 -m pip install pytest pytest-mock
      - run: mkdir local
      - run: mkdir local/keyword_features_hyperscan_databases
#      - run: export MIM_OCR_CONFIG_PATH=/code/config/test_mim_ocr_conf.yaml
#      - run: echo $MIM_OCR_CONFIG_PATH
      - run: python3.9 -m pytest tests/ --ignore=tests/optional_elements