name: Pytest
run-name: Pytest
on: [push]

env:
  MIM_OCR_CONFIG_PATH:  ${{ github.workspace }}/config/test_mim_ocr_conf.yaml
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  pytest3_9:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mim-solutions/mim-ocr_base_python3.9
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

      - run: python3.9 -m pip install -r build/requirements.txt
      - run: python3.9 -m pip install pytest pytest-mock
      - run: mkdir local
      - run: mkdir local/keyword_features_hyperscan_databases
      - run: python3.9 -m pytest tests/ --ignore=tests/optional_elements

  pytest3_9_optional:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mim-solutions/mim-ocr_base_python3.9
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

      - run: python3.9 -m pip install -r build/requirements.txt
      - run: python3.9 -m pip install pytest pytest-mock
      - run: mkdir local
      - run: mkdir local/keyword_features_hyperscan_databases
      - run: python3.9 -m pip install -r build/optional_requirements/ner_feature_requirements.txt
      - run: python3.9 -m pytest tests/optional_elements


  pytest3_10:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mim-solutions/mim-ocr_base_python3.10
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

      - run: python3.10 -m pip install -r build/requirements.txt
      - run: python3.10 -m pip install pytest pytest-mock
      - run: mkdir local
      - run: mkdir local/keyword_features_hyperscan_databases
      - run: python3.10 -m pytest tests/ --ignore=tests/optional_elements