name: lint
on: [push]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_3_9: jerzyorlowskimim/mim-ocr-fork1_base_python3.9

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    container: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_3_9 }}
    steps:
      - run: pip install flake8
      - run: flake8

